import type { Metadata } from "next";
import font from "@/helper/font";
import "./globals.css"; 
import Providers from "@/redux/Providers";
import { Toaster } from "react-hot-toast";
export const metadata: Metadata = {
  title: "Amir food ",
  description: "Generated by create next app and powered by amirkhany",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${font.className} antialiased bg-orange-50`}
      >
        <Providers>
        {children}
        <div>
          <Toaster/>
        </div>
        </Providers>
      </body>
    </html>
  );
}
